language: go

go:
  - 1.11.x
  - master
install: true
script:
  - env GO111MODULE=on go build
  - env GO111MODULE=on go vet ./...
  - env GO111MODULE=on go test -race -coverprofile=cover.out ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)