language: go

go:
  - 1.11.x
install: true
services:
  - postgresql
  - docker
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - GO111MODULE=on

before_script:
  - psql -c 'create database microapi;' -U postgres
  # If the SDK is not already cached, download it and unpack it
#  - if [ ! -d ${HOME}/google-cloud-sdk ]; then
#    curl https://sdk.cloud.google.com | bash;
#    fi
#  - echo $GCLOUD_SERVICE_KEY | base64 --decode -i > ${HOME}/gcloud-service-key.json
#  - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
#  - yes | gcloud beta auth configure-docker
#  - yes | gcloud auth configure-docker

script:
  - make install
  - go vet ./...
  - go test -race -coverprofile=cover.out ./...
  - make build

after_success:
  - bash <(curl -s https://codecov.io/bash)
