language: go

go:
  - 1.11.x
  - master
install: true
env:
  - GO111MODULE=on
  - DB_PSW=""
services:
  - postgresql
before_script:
  - psql -c 'create database microapi;' -U postgres
script:
  - make install
  - go vet ./...
  - go test -race -coverprofile=cover.out ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
