language: go

go:
  - 1.11.x
  - master

before_install:
  - make install

script:
  - make lint
  - make vet
  - go test -race -coverprofile=cover.out ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)