version: '3.7'

volumes:
  esdata01:
    driver: local

services:
  service-auth:
    image: deissh/api-micro-service-auth:${SERVICE_AUTH_TAG:-${SERVICES_TAG}}
    restart: on-failure
    depends_on:
      - postgres
    env_file:
      - .env
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]

  service-anime:
    image: deissh/api-micro-service-anime:${SERVICE_ANIME_TAG:-v1.0.0}
    restart: on-failure
    depends_on:
      - postgres
    env_file:
      - .env
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]

  service-account:
    image: deissh/api-micro-service-account:${SERVICE_ACCOUNT_TAG:-v1.0.0}
    restart: on-failure
    depends_on:
      - postgres
    env_file:
      - .env
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]

  service-friends:
    image: deissh/api-micro-service-friends:${SERVICE_FRIENDS_TAG:-v1.0.0}
    restart: on-failure
    depends_on:
      - postgres
    env_file:
      - .env
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]

  service-messages:
    image: deissh/api-micro-service-messages:${SERVICE_MESSAGES_TAG:-v1.0.0}
    restart: on-failure
    depends_on:
      - postgres
    env_file:
      - .env
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]

  service-notifications:
    image: deissh/api-micro-service-notifications:${SERVICE_NOTIFICATIONS_TAG:-v1.0.0}
    restart: on-failure
    depends_on:
      - postgres
    env_file:
      - .env
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]

  service-users:
    image: deissh/api-micro-service-users:${SERVICE_USERS_TAG:-v1.0.0}
    restart: on-failure
    depends_on:
      - postgres
    env_file:
      - .env
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]

# ==================
# important services
# ==================

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    restart: on-failure
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      placement:
        constraints: [node.role == worker]

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    restart: on-failure
    ports:
      - "5601:5601"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      placement:
        constraints: [node.role == manager]

  postgres:
    image: postgres
    restart: on-failure
    volumes:
      - /var/lib/postgresql/micro-data:/var/lib/postgresql/data
    env_file:
      - .env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      placement:
        constraints: [node.role == manager]

  nginx:
    image: deissh/api-nginx:${NGINX_TAG:-v1.0.0}
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
    depends_on:
      - service-auth
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]