basePath: /
definitions:
  handlers.CreateResponse:
    properties:
      user:
        type: string
      v:
        type: string
    type: object
  handlers.HealthResponse:
    properties:
      Health:
        $ref: '#/definitions/handlers.health'
        type: object
      v:
        description: API version
        type: string
    type: object
  handlers.PingResponse:
    properties:
      ping:
        $ref: '#/definitions/handlers.ping'
        type: object
      v:
        description: API version
        type: string
    type: object
  handlers.ResponseData:
    properties:
      data:
        type: string
      status:
        type: integer
    type: object
  handlers.health:
    properties:
      alive:
        type: boolean
    type: object
  handlers.ping:
    properties:
      id:
        type: string
      service:
        type: string
      time:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Account methods
  license: {}
  title: Service Account API
  version: "1.0"
paths:
  /_/health:
    get:
      consumes:
      - application/json
      operationId: get-service-health
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.HealthResponse'
            type: object
      summary: Show health service
  /_/ping:
    get:
      consumes:
      - application/json
      operationId: ping-service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.PingResponse'
            type: object
      summary: Ping service
  /account.create:
    get:
      consumes:
      - application/json
      description: Register new account
      operationId: create-account
      parameters:
      - description: service version
        in: query
        name: v
        type: string
      - description: user firstname
        in: body
        name: firstname
        required: true
        schema:
          $ref: '#/definitions/string'
          type: object
      - description: user lastname
        in: body
        name: lastname
        required: true
        schema:
          $ref: '#/definitions/string'
          type: object
      - description: user nickname
        in: body
        name: nickname
        required: true
        schema:
          $ref: '#/definitions/string'
          type: object
      - description: user email
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/string'
          type: object
      - description: user password
        in: body
        name: password
        required: true
        schema:
          $ref: '#/definitions/string'
          type: object
      - description: user sex
        in: body
        name: sex
        schema:
          $ref: '#/definitions/int'
          type: object
      - description: user bdate
        in: body
        name: bdate
        schema:
          $ref: '#/definitions/string'
          type: object
      - description: user picture
        in: body
        name: picture
        schema:
          $ref: '#/definitions/string'
          type: object
      - description: user desc
        in: body
        name: desc
        schema:
          $ref: '#/definitions/string'
          type: object
      - description: user status
        in: body
        name: status
        schema:
          $ref: '#/definitions/string'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.CreateResponse'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ResponseData'
            type: object
      summary: Create new account
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
swagger: "2.0"
