basePath: /
definitions:
  handlers.CreateResponse:
    properties:
      anime:
        type: string
      v:
        description: API version
        type: string
    type: object
  handlers.GetResponse:
    properties:
      anime:
        type: string
      v:
        description: API version
        type: string
    type: object
  handlers.HealthResponse:
    properties:
      Health:
        $ref: '#/definitions/handlers.health'
        type: object
      v:
        description: API version
        type: string
    type: object
  handlers.PingResponse:
    properties:
      ping:
        $ref: '#/definitions/handlers.ping'
        type: object
      v:
        description: API version
        type: string
    type: object
  handlers.RemoveResponse:
    properties:
      status:
        type: string
      v:
        description: API version
        type: string
    type: object
  handlers.ResponseData:
    properties:
      data:
        type: string
      status:
        type: integer
    type: object
  handlers.UpdateRequest:
    properties:
      anime:
        $ref: '#/definitions/handlers.anime'
        type: object
    type: object
  handlers.anime:
    properties:
      actors:
        type: string
      annotation:
        type: string
      countries:
        type: string
      description:
        type: string
      directors:
        type: string
      genres:
        type: string
      kinopoisk_id:
        type: string
      posters:
        type: string
      status:
        type: string
      studios:
        type: string
      title:
        type: string
      title_en:
        type: string
      title_or:
        type: string
      translators:
        type: string
      type:
        type: string
      world_art_id:
        type: string
      year:
        type: string
    type: object
  handlers.health:
    properties:
      alive:
        type: boolean
    type: object
  handlers.ping:
    properties:
      id:
        type: string
      service:
        type: string
      time:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Anims methods
  license: {}
  title: Service Anime API
  version: "1.0"
paths:
  /_/health:
    get:
      consumes:
      - application/json
      operationId: get-service-health
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.HealthResponse'
            type: object
      summary: Show health service
  /_/ping:
    get:
      consumes:
      - application/json
      operationId: ping-service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.PingResponse'
            type: object
      summary: Ping service
  /anime.create:
    post:
      consumes:
      - application/json
      description: Create anime and return it
      operationId: create-anime
      parameters:
      - description: anime body
        in: body
        name: anime
        required: true
        schema:
          $ref: '#/definitions/handlers.anime'
          type: object
      - description: service version
        in: query
        name: v
        type: string
      - description: user access_token
        in: query
        name: access_token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.CreateResponse'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ResponseData'
            type: object
      summary: Create anime
  /anime.get:
    get:
      consumes:
      - application/json
      description: Return info about anime by id
      operationId: get-anime
      parameters:
      - description: service version
        in: query
        name: v
        type: string
      - description: anime id
        in: query
        name: anime
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.GetResponse'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ResponseData'
            type: object
      summary: Return anime by id
  /anime.remove:
    get:
      consumes:
      - application/json
      description: Remove anime by id
      operationId: remove-anime
      parameters:
      - description: service version
        in: query
        name: v
        type: string
      - description: anime id
        in: query
        name: anime_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.RemoveResponse'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ResponseData'
            type: object
      summary: Remove anime by id
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
swagger: "2.0"
