basePath: /
definitions:
  handlers.GetResponse:
    properties:
      user:
        type: string
      v:
        description: API version
        type: string
    type: object
  handlers.HealthResponse:
    properties:
      Health:
        $ref: '#/definitions/handlers.health'
        type: object
      v:
        description: API version
        type: string
    type: object
  handlers.PingResponse:
    properties:
      ping:
        $ref: '#/definitions/handlers.ping'
        type: object
      v:
        description: API version
        type: string
    type: object
  handlers.ResponseData:
    properties:
      data:
        type: string
      status:
        type: integer
    type: object
  handlers.health:
    properties:
      alive:
        type: boolean
    type: object
  handlers.ping:
    properties:
      id:
        type: string
      service:
        type: string
      time:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Users methods
  license: {}
  title: Service Users API
  version: "1.0"
paths:
  /_/health:
    get:
      consumes:
      - application/json
      operationId: get-service-health
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.HealthResponse'
            type: object
      summary: Show health service
  /_/ping:
    get:
      consumes:
      - application/json
      operationId: ping-service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.PingResponse'
            type: object
      summary: Ping service
  /user.get:
    get:
      consumes:
      - application/json
      description: Return info about user by id
      operationId: get-user
      parameters:
      - description: service version
        in: query
        name: v
        type: string
      - description: user id
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.GetResponse'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ResponseData'
            type: object
      summary: Return user by id
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
swagger: "2.0"
